### ISSUE TITLE
resize issue of monoco area

### ISSUE THREAD

**Issue by SummerSun** [Azure-Samples/iot-devkit-web-simulator#2]
repro:
open the web simulator in a smaller screen, then drag it to a big one. 
The test area does not responsive.

See the attached image for reference.

![image](https://user-images.githubusercontent.com/5179063/30200412-5d7c5bd0-94a9-11e7-94bf-32b59930e9c1.png)

**Comment by michaeljqzq** [comment]
Thanks for feedback, fixed in 2e76cb771daaaffe8e8e57f52dc2db71f446b086
