### ISSUE TITLE
Always no tweets after shake

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/iot-devkit-web-simulator#25]
Always get no tweets after shake the DevKit...

**Comment by chyuanmsft** [comment]
Seems there's some problem with the azure function
<img width="272" alt="image" src="https://user-images.githubusercontent.com/18064616/30203368-7947cf10-94b4-11e7-91b0-f06808fecbb4.png">

**Comment by michaeljqzq** [comment]
Thanks for feedback, issue fixed
