### ISSUE TITLE
The code doesn't reflect the change of topic edit box

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/iot-devkit-web-simulator#27]
I edited the topic in the topic edit box, but the code still shows default topic
<img width="612" alt="image" src="https://user-images.githubusercontent.com/18064616/30203056-4e795926-94b3-11e7-94f4-0e830ca4c7da.png">

**Comment by michaeljqzq** [comment]
When you change the topic, you need to click the save button. And then the code in editor will reflect the change
