### ISSUE TITLE
[IE] Layout issue of the start page

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure-Samples/iot-devkit-web-simulator#5]
Browser: IE
Open the simulator in a small window, maximize the windows,  then...
![20170908-1](https://user-images.githubusercontent.com/20514459/30200667-7e0544c4-94aa-11e7-845a-d31369b094bc.png)

**Comment by michaeljqzq** [comment]
Thanks for feedback, fixed in 2e76cb771daaaffe8e8e57f52dc2db71f446b086
