### ISSUE TITLE
[Edge] The code panel re-size issue

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure-Samples/iot-devkit-web-simulator#9]
Browser: Edge

Open the simulator in a small window
![20170908-3](https://user-images.githubusercontent.com/20514459/30201215-78c15348-94ac-11e7-92cd-1c7e7190fc11.png)

maximize the windows, the code panel hasn't been re-sized according to the browser size
![20170908-4](https://user-images.githubusercontent.com/20514459/30201220-7d98f146-94ac-11e7-9583-63ff980e9a9b.png)

**Comment by michaeljqzq** [comment]
Thanks for feedback, fixed in 2e76cb771daaaffe8e8e57f52dc2db71f446b086
